image: docker:latest
services:
  - docker:dind

stages:
  - test
  - build

variables:
  REGISTRY: "registry.gitlab.com/brandonbutler/cloudflare-go"
  CONTAINER_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:latest

test:
  stage: test
  image: golang:latest
  script:
    - go version
    - go test -v
    - go build -o cloudflare
  artifacts:
    paths:
      - cloudflare
    expire_in: 1 week

build:
  stage: build
  before_script:
    - docker login $REGISTRY -u brandonbutler -p $CI_PASS
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
